languageCode = "fr-FR"
defaultContentLang = "fr"
languageLang = "fr"
defaultContentLanguage = "fr"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
title = "Nom du site / service"
baseurl = "/"

[params]
images = ["img/gopher_moi.png"]

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true